name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      
        - name : checkout
          uses : actions/checkout@v2
                      
        - name : rebuild image and deploy
          uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"

