name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name : setting discord token
          run: |
            echo { token : ${{ secrets.DISCORD_TOKEN }} } > config.json
            ls
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"

